"""Generate `sidecar/AGENTS.md` from the live registry and the compiled graphs.

    cd sidecar && uv run python devtools/draw_agents_doc.py > AGENTS.md

Generated, never hand-written, for one reason: a hand-maintained roster of
thirteen agents, eight shapes, their prompts and their tool boxes is stale the
first time anyone edits `agents.py` and forgets. Everything below is read out of
`AgentSpec`, `toolbox_for` and `CompiledStateGraph.get_graph()` at run time, so
regenerating is the only way it can be wrong.
"""

from __future__ import annotations

import sys

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent.parent))

from arcelle_sidecar.agents import (  # noqa: E402
    ALL_REGISTRY_TOOLS,
    CORE_TOOLS,
    REGISTRY,
    agent_tool_specs,
    toolbox_for,
)
from arcelle_sidecar.graphs import (  # noqa: E402
    TEMPLATES,
    build_agent_graph,
    template_for,
)

TEMPLATE_BLURB = {
    "supervisor": (
        "The tool-calling cycle, but its catalog is SPECIALISTS rather than room "
        "tools, and a guard rejects any room tool the model drifts into. The Main "
        "agent only."
    ),
    "react": (
        "The classic loop: think, call a tool, read the result, repeat, answer. "
        "The right shape when the ORDER genuinely is the model's to choose."
    ),
    "react_verify": (
        "The loop plus a ground-truth gate before the answer. If write tools ran "
        "and nothing was recorded, the answer is sent back for ONE tool-less "
        "restatement rather than letting \"I saved it\" through unchallenged."
    ),
    "route_act": (
        "Deterministic verb pick (LangGraph's Router pattern, the rule-based arm), "
        "then a bounded cycle to fill its arguments. For agents whose verbs are "
        "mutually exclusive and whose vocabulary already separates them."
    ),
    "probe_gate_act": (
        "Fire the opening tool for FREE, gate on what it said, then act. For an "
        "agent whose first move is a constant — and whose \"can't do that\" answer "
        "needs no model at all."
    ),
    "perceive_act": (
        "See, act, see again — WebVoyager's loop. The capture is deterministic "
        "(so one action costs one model round, not two) and `trim_images` keeps "
        "exactly ONE live screenshot in context."
    ),
    "chain_stage": (
        "An ORDERED chain of one-tool stages. For an agent whose prompt already "
        "prescribes the order, so the order is not the model's to choose."
    ),
    "recall_act_check": (
        "Load this agent's own prior art for free, act, check the result for "
        "failure markers, repair within a bound. The index call is always the "
        "first move, so paying a model round for it is waste."
    ),
}


def mermaid(template: str) -> str:
    raw = build_agent_graph(template).get_graph().draw_mermaid()
    # Strip the config front-matter: it renders as a stray block on GitHub.
    if raw.startswith("---"):
        raw = raw.split("---", 2)[-1]
    return raw.strip()


def main() -> None:
    out: list[str] = []
    w = out.append

    by_template: dict[str, list[str]] = {}
    for spec in REGISTRY:
        by_template.setdefault(template_for(spec.id), []).append(spec.id)

    workers = [s for s in REGISTRY if not s.main]

    w("# Arcelle agents — graphs, prompts and tools")
    w("")
    w(
        f"**{len(REGISTRY)} agents · {len(TEMPLATES)} graph shapes · "
        f"{len(ALL_REGISTRY_TOOLS)} distinct tools.**"
    )
    w("")
    w(
        "Generated by `devtools/draw_agents_doc.py` from the live registry and the "
        "compiled graphs — do not edit by hand, regenerate."
    )
    w("")

    # --- overview -----------------------------------------------------------
    w("## How a turn flows")
    w("")
    w(
        "One ask runs ONE loop — the Main agent's. Its whole catalog is its "
        "specialists; it answers greetings and general knowledge itself, and "
        "delegates anything about this room. `execute_tools` intercepts each "
        "delegation and runs that worker's **own** graph, returning only the "
        "worker's report to the main thread. Every delegation the model emits in "
        "ONE round runs in **parallel** — the batch is launched before any of it "
        "is awaited, and the reports are collected in call order — so a round "
        "costs the slowest child rather than the sum. The referent baton carries "
        "artifacts across specialists in code, so no model has to remember "
        "another's work."
    )
    w("")
    w("```mermaid")
    w("graph TD")
    w("    U([User ask]) --> M{{Main agent<br/>chat.answer · supervisor}}")
    w("    M -->|knows it| A([Answer])")
    for spec in workers:
        node = spec.id.replace(".", "_")
        w(f"    M -->|delegate| {node}[{spec.label}<br/><i>{template_for(spec.id)}</i>]")
        w(f"    {node} -->|report| M")
    w("    M --> A")
    w("```")
    w("")

    # --- shapes at a glance -------------------------------------------------
    w("## The eight shapes")
    w("")
    w("| Shape | Agents | Why this shape |")
    w("|---|---|---|")
    for t in TEMPLATES:
        ids = ", ".join(f"`{i}`" for i in by_template.get(t, [])) or "—"
        w(f"| **{t}** | {ids} | {TEMPLATE_BLURB.get(t, '')} |")
    w("")
    w(
        "Sharing is justified, not convenient: two agents share a shape only when "
        "the WORK is the same. They differ through `Flow` data — routed verbs, "
        "probe tool, failure markers, repair cap — not through branches inside a "
        "node, so the differences stay testable."
    )
    w("")

    # --- roster table -------------------------------------------------------
    w("## Roster")
    w("")
    w("| Agent | Label | Shape | Box (on top of CORE) |")
    w("|---|---|---|---|")
    for spec in REGISTRY:
        box = ", ".join(f"`{t}`" for t in spec.tools) or "— (specialists)"
        w(f"| `{spec.id}` | {spec.label} | {template_for(spec.id)} | {box} |")
    w("")
    w("### CORE — offered to every agent")
    w("")
    w(
        "The Rust base prompt teaches these by name on every turn, so the catalog "
        "must match it: live QA proved that a catalog contradicting the prompt "
        "makes the model deny its own abilities (\"I can't save files\")."
    )
    w("")
    w(" ".join(f"`{t}`" for t in CORE_TOOLS))
    w("")

    # --- per agent ----------------------------------------------------------
    w("## Each agent")
    w("")
    for spec in REGISTRY:
        t = template_for(spec.id)
        w(f"### `{spec.id}` — {spec.label}")
        w("")
        w(f"> {spec.description}")
        w("")
        w(f"**Shape:** `{t}`")
        if spec.main:
            w("")
            w(
                "**The Main agent.** It runs NO room tool — every piece of work is "
                "delegated and only the report comes back. It alone writes to the "
                "user."
            )
        w("")

        offered = sorted(toolbox_for(spec.id, set(ALL_REGISTRY_TOOLS)))
        if spec.main:
            names = sorted(
                s["function"]["name"]
                for s in agent_tool_specs(
                    web_enabled=True, served_names=set(ALL_REGISTRY_TOOLS)
                )
            )
            w("**Delegation tools:** " + " ".join(f"`{n}`" for n in names))
        else:
            box = sorted(set(spec.tools))
            w("**Own box:** " + (" ".join(f"`{t}`" for t in box) or "— CORE only"))
            w("")
            w(f"**Total offered** (CORE + box, intersected with what the host serves): {len(offered)}")
        w("")

        flow = spec.flow
        bits = []
        if flow.probe:
            bits.append(f"fires `{flow.probe}` deterministically as its first act (0 model calls)")
        if flow.stages:
            bits.append("stages: " + " → ".join(f"`{s}`" for s in flow.stages))
        if flow.actions:
            bits.append(
                "routed verbs: "
                + ", ".join(f"`{a.tool}`" for a in flow.actions)
            )
        if flow.keep:
            bits.append("kept alongside a narrow: " + ", ".join(f"`{k}`" for k in flow.keep))
        if flow.repair_cap:
            bits.append(f"repair attempts: {flow.repair_cap}")
        if flow.blockers:
            bits.append("blocked when the probe says: " + ", ".join(f"“{b}”" for b in flow.blockers))
        if bits:
            w("**Flow:** " + "; ".join(bits) + ".")
            w("")

        if spec.hints:
            w("**Routing vocabulary:** " + " ".join(f"`{h}`" for h in spec.hints))
            w("")

        w("<details><summary>System prompt</summary>")
        w("")
        w("```text")
        w((spec.prompt or "(the base prompt already covers this agent)").strip())
        w("```")
        w("")
        w("</details>")
        w("")
        w("```mermaid")
        w(mermaid(t))
        w("```")
        w("")

    # --- shapes appendix ----------------------------------------------------
    w("## Appendix — every shape, side by side")
    w("")
    for t in TEMPLATES:
        w(f"### `{t}`")
        w("")
        w(TEMPLATE_BLURB.get(t, ""))
        w("")
        w("```mermaid")
        w(mermaid(t))
        w("```")
        w("")

    w("## Invariants every shape keeps")
    w("")
    w(
        "SPEC §3.2's guarantees live in the NODE FUNCTIONS, not in the wiring, and "
        "every shape composes the same ones — so a new shape cannot quietly drop "
        "an invariant: you would have to write a new node, not draw a new edge."
    )
    w("")
    w("- The final round offers **zero tools**, so a turn always ends in an answer grounded in results already in hand.")
    w("- Only **successful** calls are memoised, so a transient failure can be retried in a later round.")
    w("- An **all-duplicate** round forces synthesis — a looping model stops burning budget on repeats.")
    w("- Cancellation is checked **between rounds and between tool calls** — Stop stops, not \"stops after the next 90-second tool\".")
    w("- A blank answer becomes \"Done.\" — but **never** when the user cancelled.")
    w("")

    print("\n".join(out))


if __name__ == "__main__":
    main()
