use super::*;

// ---------------------------------------------------------------- ART-1: the artifact write funnel
//
// "Ask before AI edits files" is OFF by the owner's decision. Nothing stands
// between a model deciding to write a document and that document being in the
// room, so the write itself has to carry the safety:
//
//   * STAGE — the bytes land in `staged_artifacts`, not in `files`. A crash or a
//     Stop between here and the commit leaves the library exactly as it was, and
//     the orphan is swept on the next room open.
//   * VALIDATE — an empty or nameless artifact is refused at the door, because
//     an empty file in the library reads as finished work (anti-fabrication).
//   * CANCEL — the token is read IMMEDIATELY before the commit, so a Stop the
//     user pressed while the model was still talking cannot land anyway.
//   * COMMIT — one transaction. Regenerating an artifact makes a new VERSION of
//     it (History), not an overwrite and not a "Deck (2).html" twin.
//
// `db::commit_staged` is the transaction; this is the caller-facing shape of it.

/// One AI-generated artifact on its way into the room. Built at the call site,
/// then `commit`ted — there is no way to get generated bytes into `files`
/// without going through the staging step, which is the point.
pub(crate) struct Artifact<'a> {
    name: String,
    mime: String,
    content: &'a str,
    prov: db::Provenance,
    cancel: Option<&'a AtomicBool>,
}

/// What a committed artifact turned out to be. `versioned` is true when this
/// write became a new version of an artifact that was already there — the
/// callers that tell the user about the save use it to say so honestly ("the
/// previous one is in History") instead of implying a brand-new file.
pub(crate) struct Written {
    pub meta: FileMeta,
    pub versioned: bool,
}

impl<'a> Artifact<'a> {
    /// An artifact with an explicit mime (a generated HTML page, a CSV).
    pub(crate) fn new(name: &str, mime: &str, content: &'a str) -> Self {
        Self {
            name: name.to_string(),
            mime: mime.to_string(),
            content,
            prov: db::Provenance::default(),
            cancel: None,
        }
    }

    /// A generated note — Markdown by default, mime derived from the name. The
    /// extension default lives here so `create_note` and `save_and_open` cannot
    /// disagree about what an extension-less name means.
    pub(crate) fn note(name: &str, content: &'a str) -> Self {
        let name = if extraction::extension_of(name).is_empty() {
            format!("{name}.md")
        } else {
            name.to_string()
        };
        let mime = note_mime(&name);
        Self::new(&name, &mime, content)
    }

    /// Which agent or command produced it.
    pub(crate) fn by(mut self, agent: &str) -> Self {
        self.prov.agent = Some(agent.to_string());
        self
    }

    /// The tool call that wrote it, when one did.
    pub(crate) fn via_tool(mut self, tool: &str) -> Self {
        self.prov.tool = Some(tool.to_string());
        self
    }

    /// The run this write belongs to (an ask id, a job id). Optional because a
    /// tool dispatched by the persistent room bridge runs behind no ask.
    pub(crate) fn during_run(mut self, run_id: Option<&str>) -> Self {
        self.prov.run_id = run_id.map(str::to_string);
        self
    }

    /// The room files this artifact was made FROM — ids, never their contents.
    pub(crate) fn from_files(mut self, ids: &[String]) -> Self {
        self.prov.source_file_ids = ids.to_vec();
        self
    }

    /// The run's cancel flag. Read once, immediately before the commit.
    pub(crate) fn cancel_with(mut self, flag: &'a AtomicBool) -> Self {
        self.cancel = Some(flag);
        self
    }

    /// The same, for callers whose flag is optional (a tool dispatched by a
    /// persistent bridge has no run behind it to stop).
    pub(crate) fn cancel_maybe(mut self, flag: Option<&'a AtomicBool>) -> Self {
        self.cancel = flag;
        self
    }

    /// Stage → validate → check the cancel token → commit.
    ///
    /// The cancel check sits between staging and committing on purpose. Checking
    /// earlier would leave a window in which a Stop is honoured everywhere
    /// except the write; checking after the commit could only ever report a file
    /// that is already in the library as if it were not.
    pub(crate) fn commit(self, conn: &Connection) -> Result<Written, String> {
        let bytes = self.content.as_bytes();
        let staged = db::stage_artifact(
            conn,
            &self.name,
            &self.mime,
            bytes,
            Some(self.content),
            &self.prov,
        )?;
        if self.cancel.map(|c| c.load(Ordering::SeqCst)).unwrap_or(false) {
            // Discarding is best-effort — the sweep on the next room open is the
            // backstop — but the REPORT must be exact: nothing was saved.
            let _ = db::discard_staged(conn, &staged.id);
            return Err(format!(
                "Stopped before \"{}\" was saved — nothing was written to the room.",
                staged.name
            ));
        }
        match db::commit_staged(conn, &staged.id) {
            Ok((meta, versioned)) => Ok(Written { meta, versioned }),
            Err(e) => {
                let _ = db::discard_staged(conn, &staged.id);
                Err(e)
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_cancelled_artifact_is_never_written_and_says_so() {
        // The whole reason staging exists: a Stop between "the model finished"
        // and "the file is in the room" must leave the room untouched, and the
        // caller must be told nothing was saved rather than getting an Ok.
        let conn = db::mem();
        let stop = AtomicBool::new(true);
        let err = Artifact::note("Minutes", "the meeting notes")
            .by("#minutes")
            .cancel_with(&stop)
            .commit(&conn)
            .map(|_| ())
            .unwrap_err();
        assert!(err.contains("nothing was written"), "got: {err}");
        assert!(db::list_files(&conn).unwrap().is_empty());
        // And no staging row is left holding the bytes.
        assert_eq!(db::sweep_staged_artifacts(&conn).unwrap(), 0);
    }

    #[test]
    fn a_child_of_a_cancelled_run_writes_no_artifact() {
        // Owner replacement #3, and his binding decision with it: cancelling a
        // PARENT blocks the child's artifact write, it does not merely sever its
        // delivery. The Studio build an agent starts is a child of the ask, and
        // the flag it hands this funnel is its own — set only because the run
        // above it was stopped (`crate::cancel`). Nothing here knows about the
        // tree, which is the point: the funnel reads a flag, and the tree is
        // what makes that flag tell the truth about the whole run.
        let conn = db::mem();
        let run = crate::cancel::Node::root("this answer");
        let studio = run.child("Flashcards");
        run.cancel();

        let flag = studio.flag();
        let err = Artifact::new("Flashcards - lease.html", "text/html", "<html>deck</html>")
            .by("Flashcards")
            .cancel_with(&flag)
            .commit(&conn)
            .map(|_| ())
            .unwrap_err();

        assert!(err.contains("nothing was written"), "got: {err}");
        assert!(
            db::list_files(&conn).unwrap().is_empty(),
            "a stopped run left an artifact in the library"
        );
        assert_eq!(db::sweep_staged_artifacts(&conn).unwrap(), 0);
    }

    #[test]
    fn a_cancel_that_arrives_after_the_commit_does_not_unsay_it() {
        // The flag is read ONCE, before the commit. A file that really is in the
        // room is reported as such — the opposite failure (claiming a save that
        // did not happen) is the one this codebase exists to prevent, but
        // claiming a failure that did not happen is just as untrue.
        let conn = db::mem();
        let stop = AtomicBool::new(false);
        let w = Artifact::note("Minutes", "body").cancel_with(&stop).commit(&conn).unwrap();
        stop.store(true, Ordering::SeqCst);
        assert_eq!(db::get_file_extracted_text(&conn, &w.meta.id).unwrap(), "body");
    }

    #[test]
    fn regenerating_a_note_versions_it_and_records_who_made_it() {
        let conn = db::mem();
        let first = Artifact::note("Weekly brief", "week one")
            .by("Documents agent")
            .via_tool("create_file")
            .during_run(Some("job-7"))
            .commit(&conn)
            .unwrap();
        assert!(!first.versioned);
        assert_eq!(first.meta.name, "Weekly brief.md", "extension-less names default to .md");

        let again = Artifact::note("Weekly brief", "week two")
            .by("Documents agent")
            .during_run(Some("job-8"))
            .commit(&conn)
            .unwrap();
        assert!(again.versioned, "a regeneration is a version");
        assert_eq!(again.meta.id, first.meta.id);
        assert_eq!(db::list_files(&conn).unwrap().len(), 1, "and never a second row");

        let prov = db::file_provenance(&conn, &first.meta.id).unwrap().unwrap();
        assert_eq!(prov.run_id.as_deref(), Some("job-8"));
        assert_eq!(prov.agent.as_deref(), Some("Documents agent"));

        let versions = db::list_file_versions(&conn, &first.meta.id).unwrap();
        assert_eq!(versions.len(), 1);
        let older = versions[0].provenance.as_ref().unwrap();
        assert_eq!(older.run_id.as_deref(), Some("job-7"));
        assert_eq!(older.tool.as_deref(), Some("create_file"));
    }

    #[test]
    fn source_files_are_recorded_as_ids_only() {
        let conn = db::mem();
        let src = db::add_file(&conn, "lease.pdf", "the tenant pays rent on the first");
        let w = Artifact::note("Lease summary", "a summary")
            .by("#summarize")
            .from_files(&[src.clone()])
            .commit(&conn)
            .unwrap();
        let prov = db::file_provenance(&conn, &w.meta.id).unwrap().unwrap();
        assert_eq!(prov.source_file_ids, vec![src]);
        // Nothing about the source's CONTENT rides along.
        let raw: String = conn
            .query_row(
                "SELECT provenance FROM files WHERE id = ?1 AND trashed_at IS NULL",
                [&w.meta.id],
                |r| r.get(0),
            )
            .unwrap();
        assert!(!raw.contains("tenant"), "provenance carries ids, not room content");
    }

    #[test]
    fn a_user_can_go_back_to_an_earlier_generation_and_the_credit_goes_back_too() {
        // The net under an AI that writes without asking: the run that replaced
        // your document is undoable, and after the undo the file no longer
        // claims to have been written by the run whose words are gone.
        let conn = db::mem();
        let v1 = Artifact::note("Brief.md", "the first brief")
            .by("Research agent")
            .during_run(Some("run-1"))
            .commit(&conn)
            .unwrap();
        Artifact::note("Brief.md", "a rewrite nobody asked for")
            .by("Documents agent")
            .during_run(Some("run-2"))
            .commit(&conn)
            .unwrap();
        assert_eq!(
            db::get_file_extracted_text(&conn, &v1.meta.id).unwrap(),
            "a rewrite nobody asked for"
        );

        let older = db::list_file_versions(&conn, &v1.meta.id).unwrap();
        assert_eq!(older.len(), 1);
        let restored = super::super::restore_version_into(&conn, &older[0].id).unwrap();

        assert_eq!(restored, v1.meta.id);
        assert_eq!(db::get_file_extracted_text(&conn, &v1.meta.id).unwrap(), "the first brief");
        let head = db::file_provenance(&conn, &v1.meta.id).unwrap().unwrap();
        assert_eq!(head.agent.as_deref(), Some("Research agent"));
        assert_eq!(head.run_id.as_deref(), Some("run-1"));
        // And the restore is itself undoable — the rewrite is now the version.
        let after = db::list_file_versions(&conn, &v1.meta.id).unwrap();
        assert_eq!(after.len(), 2);
        assert_eq!(after[0].cause, "Restored");
        assert_eq!(
            after[0].provenance.as_ref().unwrap().run_id.as_deref(),
            Some("run-2"),
            "the snapshot taken on the way past keeps the rewrite's own credit"
        );
    }

    #[test]
    fn restoring_a_hand_typed_state_clears_the_ai_credit() {
        // A person's own file has no provenance. If the AI rewrites it and the
        // person restores their version, the file must stop being attributed to
        // the AI — a stale credit here is the same lie as a missing one.
        let conn = db::mem();
        let mine = db::insert_file(&conn, "Plan.md", "text/markdown", b"my plan", Some("my plan"), "generated")
            .unwrap();
        Artifact::note("Plan.md", "the AI's plan")
            .by("Documents agent")
            .commit(&conn)
            .unwrap();
        assert!(db::file_provenance(&conn, &mine.id).unwrap().is_some());

        let v = db::list_file_versions(&conn, &mine.id).unwrap();
        super::super::restore_version_into(&conn, &v[0].id).unwrap();
        assert_eq!(db::get_file_extracted_text(&conn, &mine.id).unwrap(), "my plan");
        assert!(
            db::file_provenance(&conn, &mine.id).unwrap().is_none(),
            "no run wrote what is on screen now, so nothing is credited"
        );
    }

    #[test]
    fn an_empty_generation_is_refused_rather_than_saved_as_a_blank_file() {
        let conn = db::mem();
        let err = Artifact::note("Report", "").commit(&conn).map(|_| ()).unwrap_err();
        assert!(err.contains("Nothing was generated"), "got: {err}");
        assert!(db::list_files(&conn).unwrap().is_empty());
    }
}
