import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

const REQUIRED_METHODS = [
  "thread/start",
  "turn/start",
  "turn/interrupt",
  "item/started",
  "item/completed",
  "turn/completed",
] as const;

export interface CodexSchemaCompatibility {
  compatible: boolean;
  files: number;
  missingMethods: string[];
  collaborationEvents: boolean;
  dynamicTools: boolean;
}

function collectStrings(value: unknown, output: Set<string>): void {
  if (typeof value === "string") {
    output.add(value);
    return;
  }
  if (Array.isArray(value)) {
    collectArrayStrings(value, output);
    return;
  }
  if (typeof value === "object" && value !== null) {
    collectObjectStrings(value as Record<string, unknown>, output);
  }
}

function collectArrayStrings(values: readonly unknown[], output: Set<string>): void {
  for (const value of values) collectStrings(value, output);
}

function collectObjectStrings(value: Record<string, unknown>, output: Set<string>): void {
  for (const [key, entry] of Object.entries(value)) {
    output.add(key);
    collectStrings(entry, output);
  }
}

/** Inspect exactly the JSON schema generated by the installed Codex binary. */
export async function inspectCodexSchemaDirectory(root: string): Promise<CodexSchemaCompatibility> {
  const entries = await readdir(root, { recursive: true, withFileTypes: true });
  const files = entries.filter(isCodexSchemaFile);
  const strings = new Set<string>();
  const parsedFiles = await collectCodexSchemaStrings(files, strings);
  return codexSchemaCompatibility(files.length, parsedFiles, strings);
}

interface CodexSchemaFile {
  readonly name: string;
  readonly path: string;
  readonly parentPath?: string;
  isFile(): boolean;
}

function isCodexSchemaFile(entry: CodexSchemaFile): boolean {
  return entry.isFile() && entry.name.endsWith(".json");
}

async function collectCodexSchemaStrings(
  files: readonly CodexSchemaFile[],
  strings: Set<string>
): Promise<number> {
  let parsed = 0;
  for (const file of files) {
    try {
      const parent = file.parentPath ?? file.path;
      collectStrings(JSON.parse(await readFile(path.join(parent, file.name), "utf8")), strings);
      parsed += 1;
    } catch {
      // A partial/corrupt generated schema makes the probe fail closed below.
    }
  }
  return parsed;
}

function codexSchemaCompatibility(
  fileCount: number,
  parsedFiles: number,
  strings: ReadonlySet<string>
): CodexSchemaCompatibility {
  const missingMethods = REQUIRED_METHODS.filter((method) => !strings.has(method));
  return {
    compatible: parsedFiles > 0 && parsedFiles === fileCount && missingMethods.length === 0,
    files: parsedFiles,
    missingMethods,
    collaborationEvents: strings.has("collabToolCall") || strings.has("collabAgentToolCall") || strings.has("collab_tool_call"),
    dynamicTools: strings.has("item/tool/call") || strings.has("dynamicToolCall"),
  };
}
