import { readFile, readdir } from "node:fs/promises";
import path from "node:path";

const REQUIRED_METHODS = [
  "thread/start",
  "turn/start",
  "turn/interrupt",
  "item/started",
  "item/completed",
  "turn/completed",
] as const;

export interface CodexSchemaCompatibility {
  compatible: boolean;
  files: number;
  missingMethods: string[];
  collaborationEvents: boolean;
  dynamicTools: boolean;
}

function collectStrings(value: unknown, output: Set<string>): void {
  if (typeof value === "string") {
    output.add(value);
    return;
  }
  if (Array.isArray(value)) {
    for (const entry of value) collectStrings(entry, output);
    return;
  }
  if (typeof value === "object" && value !== null) {
    for (const [key, entry] of Object.entries(value as Record<string, unknown>)) {
      output.add(key);
      collectStrings(entry, output);
    }
  }
}

/** Inspect exactly the JSON schema generated by the installed Codex binary. */
export async function inspectCodexSchemaDirectory(root: string): Promise<CodexSchemaCompatibility> {
  const entries = await readdir(root, { recursive: true, withFileTypes: true });
  const files = entries.filter((entry) => entry.isFile() && entry.name.endsWith(".json"));
  const strings = new Set<string>();
  let parsedFiles = 0;
  for (const entry of files) {
    const parent = entry.parentPath ?? entry.path;
    try {
      collectStrings(JSON.parse(await readFile(path.join(parent, entry.name), "utf8")), strings);
      parsedFiles += 1;
    } catch {
      // A partial/corrupt generated schema makes the probe fail closed below.
    }
  }
  const missingMethods = REQUIRED_METHODS.filter((method) => !strings.has(method));
  return {
    compatible: parsedFiles > 0 && parsedFiles === files.length && missingMethods.length === 0,
    files: parsedFiles,
    missingMethods,
    collaborationEvents: strings.has("collabToolCall") || strings.has("collabAgentToolCall") || strings.has("collab_tool_call"),
    dynamicTools: strings.has("item/tool/call") || strings.has("dynamicToolCall"),
  };
}
