import * as React from "react";
import { parseHTML } from "linkedom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { WSState } from "./state";

const bridge = vi.hoisted(() => ({ appDiag: vi.fn(), feedbackDraft: vi.fn(), openUrl: vi.fn() }));
vi.mock("../api", () => ({ api: { appDiag: bridge.appDiag, feedbackDraft: bridge.feedbackDraft } }));
vi.mock("../platform", () => ({ openUrl: bridge.openUrl }));
vi.mock("../icons", () => ({ SparklesIcon: () => null }));
vi.mock("../settings/useFocusTrap", () => ({ useFocusTrap: () => ({ modalRef: { current: null }, onModalKeyDown: vi.fn() }) }));
import FeedbackModal from "./FeedbackModal";

const { act, createElement } = React;
const keys=["window","document","navigator","HTMLElement","HTMLTextAreaElement","HTMLInputElement","Event","React","IS_REACT_ACT_ENVIRONMENT"] as const;
const originals=Object.fromEntries(keys.map(key=>[key,Reflect.get(globalThis,key)]));
function state(overrides:Record<string,unknown>={}) { return { errorLogRef:{current:[{at:"10:00",text:"File secret.txt failed"}]},setShowFeedback:vi.fn(),pushToast:vi.fn(),...overrides} as unknown as WSState; }
async function flush(){await act(async()=>{await Promise.resolve();await Promise.resolve();});}
async function render(s:WSState, clipboard=vi.fn().mockResolvedValue(undefined)){const p=parseHTML("<html><body><div id='root'></div></body></html>");const document=p.document as unknown as Document;const window=p.window as unknown as Window & typeof globalThis;for(const [k,v]of Object.entries({window,document,navigator:{...window.navigator,userAgent:"Vitest",clipboard:{writeText:clipboard}},HTMLElement:window.HTMLElement,HTMLTextAreaElement:window.HTMLTextAreaElement,HTMLInputElement:window.HTMLInputElement,Event:window.Event,React,IS_REACT_ACT_ENVIRONMENT:true})){if(k==="navigator")Object.defineProperty(globalThis,k,{configurable:true,writable:true,value:v});else Reflect.set(globalThis,k,v);}const {createRoot}=await import("react-dom/client");const host=document.getElementById("root");if(!host)throw Error("root");const root=createRoot(host);await act(async()=>root.render(createElement(FeedbackModal,{s})));await flush();return{host,root,window,clipboard};}
function props<T>(n:Element):T{const k=Object.getOwnPropertyNames(n).find(x=>x.startsWith("__reactProps"));if(!k)throw Error("props");return(n as unknown as Record<string,unknown>)[k]as T;}
async function change(n:Element,value:string|boolean){await act(async()=>props<{onChange:(e:{target:{value:string;checked:boolean}})=>void}>(n).onChange({target:{value:String(value),checked:Boolean(value)}}));await flush();}
async function click(n:Element,w:Window&typeof globalThis){await act(async()=>n.dispatchEvent(new w.Event("click",{bubbles:true})));await flush();}
function button(h:Element,label:string){const b=[...h.querySelectorAll("button")].find(x=>x.textContent?.includes(label));if(!b)throw Error(label);return b as HTMLButtonElement;}
beforeEach(()=>{bridge.appDiag.mockReset().mockResolvedValue({version:"1.2",os:"macOS",arch:"arm64",repo:"owner/repo"});bridge.feedbackDraft.mockReset();bridge.openUrl.mockReset();});
afterEach(()=>{for(const[k,v]of Object.entries(originals)){if(v===undefined)Reflect.deleteProperty(globalThis,k);else Reflect.set(globalThis,k,v);}});
describe("FeedbackModal",()=>{
 it("drafts locally from the raw report",async()=>{const s=state();bridge.feedbackDraft.mockResolvedValue({title:"Bug",body:"Steps"});const v=await render(s);const text=v.host.querySelectorAll<HTMLTextAreaElement>("textarea");await change(text[0]!,"rough note");await click(button(v.host,"Draft it"),v.window);expect(bridge.feedbackDraft).toHaveBeenCalledWith("rough note");await act(async()=>v.root.unmount());});
 it("opens a normal issue then closes, and reports open failures",async()=>{const s=state();const v=await render(s);const inputs=v.host.querySelectorAll<HTMLInputElement>("input");const text=v.host.querySelectorAll<HTMLTextAreaElement>("textarea");await change(inputs[0]!,"Title");await change(text[1]!,"Body");await click(button(v.host,"Open GitHub"),v.window);expect(bridge.openUrl).toHaveBeenCalledWith(expect.stringContaining("issues/new?title=Title"));expect(s.setShowFeedback).toHaveBeenCalledWith(false);await act(async()=>v.root.unmount());const failed=state();bridge.openUrl.mockRejectedValueOnce(new Error("browser"));const f=await render(failed);const fi=f.host.querySelectorAll<HTMLInputElement>("input");const ft=f.host.querySelectorAll<HTMLTextAreaElement>("textarea");await change(fi[0]!,"Title");await change(ft[1]!,"Body");await click(button(f.host,"Open GitHub"),f.window);expect(failed.pushToast).toHaveBeenCalledWith("error",expect.stringContaining("browser"));await act(async()=>f.root.unmount());});
 it("closes on cancel, backdrop, and Escape unless drafting",async()=>{const s=state();const v=await render(s);await click(button(v.host,"Cancel"),v.window);expect(s.setShowFeedback).toHaveBeenCalledWith(false);await act(async()=>v.root.unmount());});
 it("shows selected error logs and keeps clipboard failures local",async()=>{const s=state();const clipboard=vi.fn().mockResolvedValue(undefined);const v=await render(s,clipboard);const inputs=v.host.querySelectorAll<HTMLInputElement>("input");const text=v.host.querySelectorAll<HTMLTextAreaElement>("textarea");await change(inputs[2]!,true);expect(v.host.textContent).toContain("File secret.txt failed");await change(inputs[0]!,"Title");await change(text[1]!,"Body");await click(button(v.host,"Copy"),v.window);expect(clipboard).toHaveBeenCalledWith(expect.stringContaining("Title\n\nBody"));expect(s.pushToast).toHaveBeenCalledWith("success",expect.stringContaining("Copied"));await act(async()=>v.root.unmount());const copyFailure=state();const c=await render(copyFailure,vi.fn().mockRejectedValue(new Error("clipboard denied")));const ci=c.host.querySelectorAll<HTMLInputElement>("input");const ct=c.host.querySelectorAll<HTMLTextAreaElement>("textarea");await change(ci[0]!,"Title");await change(ct[1]!,"Body");await click(button(c.host,"Copy"),c.window);expect(copyFailure.pushToast).toHaveBeenCalledWith("error",expect.stringContaining("clipboard denied"));await act(async()=>c.root.unmount());const draftFailure=state();bridge.feedbackDraft.mockRejectedValueOnce(new Error("local model failed"));const d=await render(draftFailure);const raw=d.host.querySelectorAll<HTMLTextAreaElement>("textarea")[0]!;await change(raw,"rough note");await click(button(d.host,"Draft it"),d.window);expect(draftFailure.pushToast).toHaveBeenCalledWith("error",expect.stringContaining("local model failed"));await act(async()=>d.root.unmount());});
 it("uses a title-only link and copies the body when an issue URL would be oversized",async()=>{const s=state();const clipboard=vi.fn().mockResolvedValue(undefined);const v=await render(s,clipboard);const inputs=v.host.querySelectorAll<HTMLInputElement>("input");const text=v.host.querySelectorAll<HTMLTextAreaElement>("textarea");await change(inputs[0]!,"Title");await change(text[1]!,"x".repeat(6000));await click(button(v.host,"Open GitHub"),v.window);expect(clipboard).toHaveBeenCalledWith("x".repeat(6000)+"\n\n---\nArcelle 1.2 · macOS (arm64)");expect(bridge.openUrl).toHaveBeenCalledWith("https://github.com/owner/repo/issues/new?title=Title");expect(s.pushToast).toHaveBeenCalledWith("info",expect.stringContaining("too long"));expect(s.setShowFeedback).toHaveBeenCalledWith(false);await act(async()=>v.root.unmount());});
 it("closes through the backdrop and capture-phase Escape",async()=>{const backdrop=state();const b=await render(backdrop);await click(b.host.firstElementChild!,b.window);expect(backdrop.setShowFeedback).toHaveBeenCalledWith(false);await act(async()=>b.root.unmount());const escaped=state();const e=await render(escaped);const event=new e.window.Event("keydown",{bubbles:true});Object.defineProperty(event,"key",{value:"Escape"});e.window.dispatchEvent(event);await flush();expect(escaped.setShowFeedback).toHaveBeenCalledWith(false);await act(async()=>e.root.unmount());});
});
