/**
 * The compile-checked list of every valid IPC channel name — both directions:
 * `keyof Commands` (`ipc-contract.ts`, renderer→main `invoke()`) and `keyof
 * EventPayloads` (`events.ts`, main→renderer `on()`).
 *
 * ============================================================================
 * WHY AN OBJECT LITERAL, NOT A GENERATED ARRAY
 * ============================================================================
 * TypeScript interface/type keys do not survive compilation — there is no
 * `Object.keys(Commands)` to call at runtime — so SOMETHING has to turn "the
 * keys of a type" into a real array a preload script can check an untrusted
 * string against. The two obvious ways to do that are:
 *
 *   (a) a generator script that regex-scrapes `ipc-contract.ts`/`events.ts`
 *       into a committed array, plus a test that re-scrapes and diffs; or
 *   (b) a `Record<keyof T, true>` OBJECT LITERAL, whose keys are then read off
 *       with `Object.keys` at module load.
 *
 * This file uses (b). `Record<K, true>` on an object literal rejects BOTH a
 * missing key and an excess one, so drift is a COMPILE error in `npm run
 * typecheck` — not a test that has to remember to re-derive, and not a
 * generator someone can forget to re-run. (a) was the other candidate's
 * approach and it works, but its guarantee is only as good as two hand-copied
 * ~10-line regexes staying byte-identical between the generator and its drift
 * test, and it cannot catch anything until the suite runs.
 *
 * ============================================================================
 * WHY ITS OWN FILE, IMPORTING NOTHING BUT TYPES
 * ============================================================================
 * `electron/preload/index.ts` needs this exact list to build its channel
 * allowlist (D10: "reject unknown channels rather than blindly forwarding any
 * string the renderer sends"), and `electron/main/ipc/registry.ts` needs the
 * same list for its completeness diff. `registry.ts` pulls in the whole
 * main-process module graph (`roomManager.ts`,
 * `better-sqlite3-multiple-ciphers`, `sttTools.ts`, …) — native bindings and
 * Node-only code that must never be bundled into a preload script. One shared,
 * dependency-free source of truth is what lets both sides import the SAME list
 * instead of each keeping a copy that can silently diverge.
 */

import type { Commands } from "./ipc-contract.js";
import type { EventPayloads } from "./events.js";

const ALL_COMMANDS_TYPED: { [K in keyof Commands]: true } = {
  add_memory: true,
  add_privacy_block: true,
  ai_action: true,
  ai_action_prompts: true,
  ai_status: true,
  app_diag: true,
  app_version: true,
  approve_mcp: true,
  ask: true,
  audio_peaks: true,
  browser_clear_journal: true,
  browser_clear_scope: true,
  browser_close_tab: true,
  browser_focus_app: true,
  browser_go: true,
  browser_info: true,
  browser_journal: true,
  browser_navigate: true,
  browser_new_tab: true,
  browser_page_selection: true,
  browser_page_text: true,
  browser_peek: true,
  browser_preview: true,
  browser_retry_protection: true,
  browser_save_page: true,
  browser_search: true,
  browser_search_summary: true,
  browser_select_tab: true,
  browser_set_bounds: true,
  browser_set_takeover: true,
  browser_tabs: true,
  browser_verify_private: true,
  cancel_ask: true,
  cancel_job: true,
  cancel_media_download: true,
  change_password: true,
  clear_recent: true,
  close_room: true,
  compact_room: true,
  compose_skill: true,
  compose_workflow: true,
  connect_ai_provider: true,
  create_chat: true,
  create_folder: true,
  create_room: true,
  create_sealed_package: true,
  convert_legacy_room: true,
  create_room_checkpoint: true,
  create_sketch: true,
  create_skill: true,
  decode_file_text: true,
  delete_chat: true,
  delete_file_permanently: true,
  delete_file_version: true,
  delete_files_permanently: true,
  delete_folder: true,
  delete_job: true,
  delete_memory: true,
  delete_message: true,
  delete_model: true,
  delete_room_checkpoint: true,
  delete_skill: true,
  delete_skill_resource: true,
  delete_workflow: true,
  dialog_message: true,
  dialog_open: true,
  dialog_save: true,
  dict_cancel: true,
  dict_push_audio: true,
  dict_start: true,
  dict_stop: true,
  disconnect_ai_provider: true,
  duplicate_room: true,
  empty_trash: true,
  engine_capabilities: true,
  engine_preflight: true,
  engine_support_matrix: true,
  ensure_embed_model: true,
  export_all: true,
  export_file: true,
  export_skill_folder: true,
  export_sketch_png: true,
  export_sketch_svg: true,
  feedback_draft: true,
  file_versions_kept: true,
  front_page: true,
  front_page_suggestions: true,
  generate_ui_text: true,
  get_file_content: true,
  get_file_provenance: true,
  get_file_version: true,
  get_job_step_artifact: true,
  get_mcp_auto_approve: true,
  get_mcp_connector_powers: true,
  get_mcp_outbound_unmask: true,
  get_messages: true,
  get_ollama_url: true,
  get_podcast: true,
  get_setting: true,
  get_skill: true,
  get_skill_resource: true,
  get_workflow_runs: true,
  get_workflow_schedule: true,
  grounding_model_for_room: true,
  handoff_chat: true,
  has_recovery_key: true,
  harness_approve: true,
  harness_cancel: true,
  harness_capabilities: true,
  harness_cloud_writeback: true,
  harness_restore_baseline_copies: true,
  harness_rollback: true,
  harness_start: true,
  import_audio_bytes: true,
  import_files: true,
  import_sealed_package: true,
  inspect_sealed_package: true,
  import_image_bytes: true,
  import_link: true,
  import_media_url: true,
  import_search_result: true,
  import_skill_folder: true,
  list_ai_providers: true,
  list_chat_commands: true,
  list_chats: true,
  list_create_models: true,
  list_engine_models: true,
  list_file_versions: true,
  list_files: true,
  list_folders: true,
  list_jobs: true,
  list_media_formats: true,
  list_memories: true,
  list_neural_voices: true,
  list_recent: true,
  list_roles: true,
  list_room_checkpoints: true,
  list_scripts: true,
  list_skills: true,
  list_specialists: true,
  list_stranded_checkpoints: true,
  list_trashed_files: true,
  list_workflows: true,
  locate_in_image: true,
  mcp_apply_config: true,
  mcp_get_config: true,
  mcp_get_tool_prefs: true,
  mcp_oauth_authorize: true,
  mcp_oauth_sign_out: true,
  mcp_oauth_status: true,
  mcp_provision_runtime: true,
  mcp_registry_optin_status: true,
  mcp_registry_search: true,
  mcp_remove_server: true,
  mcp_runtime_for_command: true,
  mcp_set_server_enabled: true,
  mcp_set_tool_enabled: true,
  mcp_status: true,
  memory_suggestion: true,
  menu_sync: true,
  model_capabilities: true,
  move_file_to_folder: true,
  move_files_to_folder: true,
  office_html: true,
  open_html_in_browser: true,
  open_ollama: true,
  open_path: true,
  open_room: true,
  open_room_with_recovery: true,
  open_scratch_pad: true,
  open_url: true,
  pin_file_version: true,
  preview_podcast_voice: true,
  privacy_preview: true,
  privacy_status: true,
  probe_video_meta: true,
  pull_model: true,
  quicklook_preview: true,
  quit_guard_confirm: true,
  quit_guard_rearm: true,
  rec_chapter_add: true,
  rec_chapter_set: true,
  rec_correct_range: true,
  rec_delete_range: true,
  rec_export_clean: true,
  rec_get: true,
  rec_highlight_add: true,
  rec_item_delete: true,
  rec_live_status: true,
  rec_note_add: true,
  rec_note_set: true,
  rec_pause: true,
  rec_push_audio: true,
  rec_read_start: true,
  rec_resume: true,
  rec_retranscribe: true,
  rec_set_live_stt: true,
  rec_set_live_translate: true,
  rec_set_speaker_name: true,
  rec_start: true,
  rec_stop: true,
  rec_translate: true,
  recommended_models: true,
  regenerate_leash_token: true,
  remove_privacy_entity: true,
  remove_recent: true,
  rename_chat: true,
  rename_file: true,
  rename_folder: true,
  rename_room: true,
  register_workspace_copy: true,
  resolve_agent_ui: true,
  resolve_edit_approval: true,
  resolve_mcp_call: true,
  rescan_workspace_room: true,
  resolve_script_run: true,
  restore_file: true,
  restore_file_version: true,
  restore_files: true,
  resume_job: true,
  retranscribe_file: true,
  reveal_item_in_dir: true,
  reveal_logs: true,
  rollback_room_checkpoint: true,
  room_graph: true,
  room_info: true,
  room_storage_usage: true,
  room_server_status: true,
  run_command: true,
  run_script: true,
  run_workflow: true,
  save_generated_file: true,
  save_sketch: true,
  save_skill_resource: true,
  save_video_frame: true,
  save_workflow: true,
  search_all: true,
  set_cell: true,
  set_file_in_library: true,
  set_mcp_auto_approve: true,
  set_mcp_connector_power: true,
  set_mcp_outbound_unmask: true,
  set_mcp_registry_optin: true,
  set_ollama_url: true,
  set_podcast_cast: true,
  set_privacy_concepts: true,
  set_privacy_global: true,
  set_privacy_room: true,
  set_room_server: true,
  set_script_schedule: true,
  set_setting: true,
  set_skill_enabled: true,
  set_unsaved_edits: true,
  set_workflow_pinned: true,
  set_workflow_schedule: true,
  set_workflow_status: true,
  set_workspace_watcher_polling: true,
  shape_text: true,
  skill_agent_ids: true,
  skill_import_conflict: true,
  slide_preview: true,
  speak_text_neural: true,
  stage_preview_html: true,
  start_create_job: true,
  start_deep_summary: true,
  start_download_job: true,
  start_podcast_audio_job: true,
  start_privacy_scan: true,
  start_shot_list_job: true,
  start_studio_job: true,
  stt_cancel_download: true,
  stt_delete_model: true,
  stt_download_model: true,
  stt_status: true,
  story_add_cast: true,
  story_add_cast_many: true,
  story_add_shot: true,
  story_apply_split: true,
  story_board: true,
  story_create_list: true,
  story_delete_list: true,
  story_documents: true,
  story_film_plan: true,
  story_pictures: true,
  story_plan_split: true,
  story_read_cast_file: true,
  story_remove_cast: true,
  story_remove_shot: true,
  story_reorder_shots: true,
  story_set_face: true,
  story_set_shape: true,
  story_text_from_file: true,
  story_update_cast: true,
  story_update_list: true,
  story_update_shot: true,
  studio_prompts: true,
  suggest_file_meta: true,
  take_pending_open: true,
  take_rec_recovery_error: true,
  test_ollama_url: true,
  touchid_disable: true,
  touchid_enable: true,
  touchid_has: true,
  touchid_open: true,
  trash_file: true,
  trash_files: true,
  update_docx_text: true,
  update_file_content: true,
  update_memory: true,
  update_skill: true,
  update_workflow: true,
  updater_check: true,
  updater_install: true,
  validate_workflow: true,
  video_trim: true,
  voice_forget: true,
  voices_list: true,
  warm_model: true,
  web_search_test: true,
  workflow_templates: true,
  write_recovery_key: true,
  workspace_watcher_status: true,
};

/**
 * The same compile-checked treatment for `events.ts`'s `EventPayloads` — the
 * main→renderer direction. A mapped `Record<K, true>` works identically over a
 * `type` and an `interface`, so there is no reason for the event list to be a
 * hand-copied array with only a length pin behind it (which is what the other
 * candidate shipped: a rename in `events.ts` would have kept the count at 59
 * and drifted silently).
 */
const ALL_EVENTS_TYPED: { [K in keyof EventPayloads]: true } = {
  "browser-journal": true,
  "browser-navigated": true,
  "browser-searched": true,
  "browser-blocked": true,
  "browser-download": true,
  "browser-download-oversize": true,
  "runtime-progress": true,
  "mcp-oauth-url": true,
  "dict-partial": true,
  "stt-download-progress": true,
  "stt-progress": true,
  "ocr-progress": true,
  "open-room-file": true,
  "room-rolled-back": true,
  "ask-delta": true,
  "sketch-drawn": true,
  "ask-step": true,
  "ask-lane": true,
  "ask-plan": true,
  "ask-agent": true,
  "ask-step-status": true,
  "ask-round": true,
  "ask-report": true,
  "ask-privacy": true,
  "ask-token-usage": true,
  "privacy-scan": true,
  "studio-step": true,
  "job-progress": true,
  "workflow-node": true,
  "workflows-changed": true,
  "skills-changed": true,
  "memories-changed": true,
  "script-approve-request": true,
  "import-progress": true,
  "agent-open-file": true,
  "agent-annotate": true,
  "file-updated": true,
  "assistant-organized": true,
  "room-files-changed": true,
  "mcp-approve-request": true,
  "edit-approve-request": true,
  "mcp-status": true,
  "rec-read-done": true,
  "rec-partial": true,
  "rec-segment": true,
  "rec-segment-drop": true,
  "rec-relabel": true,
  "rec-level": true,
  "rec-state": true,
  "rec-save-progress": true,
  "rec-source": true,
  "rec-error": true,
  "rec-live-translation": true,
  "rec-translate-progress": true,
  "rec-retranscribe": true,
  "quit-requested": true,
  "menu-action": true,
  "ytdlp-progress": true,
  "agent-ui-request": true,
  // `events.ts`'s trailing "(59 channels total)" comment predates this one and
  // is stale — the TYPE has 60 keys. `pull-progress` is real and live
  // (`ollamaModels.ts`'s `pull_model`, `sttTools.ts`'s `stt_download_model`
  // and `moonshotCmds.ts`'s `ensure_embed_model` all `event.sender.send` it),
  // so leaving it off the allowlist would refuse a renderer's own
  // model-download progress subscription in the preload. The compile check
  // above is what surfaced it: a hand-copied 59-entry list type-checks against
  // nothing and would have shipped the gap silently.
  "pull-progress": true,
  "harness-event": true,
};

/** Runtime array of every valid `invoke()` channel name. */
export const ALL_COMMAND_NAMES: readonly (keyof Commands)[] = Object.keys(
  ALL_COMMANDS_TYPED
) as (keyof Commands)[];

/** Runtime array of every valid `on()` event channel name. */
export const ALL_EVENT_NAMES: readonly (keyof EventPayloads)[] = Object.keys(
  ALL_EVENTS_TYPED
) as (keyof EventPayloads)[];

/** The command list as a `Set`, for O(1) allowlist membership checks. A `Set`,
 * never a plain `{}` lookup object, so an externally-controlled channel string
 * can never be checked with `in` / bracket indexing against something that has
 * a `__proto__`/`constructor` own key. */
export const COMMAND_CHANNEL_SET: ReadonlySet<string> = new Set<string>(ALL_COMMAND_NAMES);

/** The event list as a `Set`, same reasoning as {@link COMMAND_CHANNEL_SET}. */
export const EVENT_CHANNEL_SET: ReadonlySet<string> = new Set<string>(ALL_EVENT_NAMES);

/** Is `channel` a real `Commands` key — i.e. safe to hand to
 * `ipcRenderer.invoke`? A plain `string` parameter on purpose: this is the
 * boundary function a caller hands an UNTRUSTED, renderer-supplied value to. */
export function isKnownCommandChannel(channel: string): channel is keyof Commands {
  return COMMAND_CHANNEL_SET.has(channel);
}

/** Is `channel` a real `EventPayloads` key — i.e. safe to `ipcRenderer.on` /
 * `removeListener` against? Same untrusted-input contract as
 * {@link isKnownCommandChannel}. */
export function isKnownEventChannel(channel: string): channel is keyof EventPayloads {
  return EVENT_CHANNEL_SET.has(channel);
}
