#!/usr/bin/env bash
# Release preflight: everything that must be true BEFORE `scripts/release.sh`.
#
# Why this script exists: release.sh reads the version from ONE file
# (tauri.conf.json) and trusts it. Seven files carry that version, and a
# release has already shipped with one of them stale (v0.14.0's
# sidecar/uv.lock still said 0.13.0). Nothing ran the test suites either, so a
# red build could sail through to a published GitHub release.
#
# Usage:
#   scripts/preflight.sh            # checks + type-check + every suite (minutes)
#   scripts/preflight.sh --checks   # versions + changelog only, no suites
#   scripts/preflight.sh --suites   # every suite only — this is `npm test`
#
# Nothing here is automatic: no hook installs this. Run it yourself before you
# tag (see RELEASING.md § 2).
set -uo pipefail
cd "$(dirname "$0")/.."

CHECKS_ONLY=0
SUITES_ONLY=0
case "${1:-}" in
  --checks) CHECKS_ONLY=1 ;;
  --suites) SUITES_ONLY=1 ;;
  "") ;;
  *) echo "usage: scripts/preflight.sh [--checks|--suites]" >&2; exit 2 ;;
esac

FAILED=0
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
bad()  { printf '  \033[31m✗\033[0m %s\n' "$1"; FAILED=1; }
step() { printf '\n▶ %s\n' "$1"; }

# ---------------------------------------------------------------- versions ---
# The source of truth is tauri.conf.json — the same file release.sh reads.
VER="$(node -p "require('./src-tauri/tauri.conf.json').version" 2>/dev/null)"
if [[ -z "$VER" ]]; then
  echo "✗ Could not read the version from src-tauri/tauri.conf.json (is node on PATH?)" >&2
  exit 1
fi

if [[ $SUITES_ONLY -eq 0 ]]; then
  step "Version agreement (expecting ${VER})"

  check_version() {  # <label> <found>
    if [[ "$2" == "$VER" ]]; then ok "$1 — $2"; else bad "$1 — ${2:-<not found>} (expected ${VER})"; fi
  }

  # Hand-edited, in the order RELEASING.md lists them.
  check_version "package.json" \
    "$(node -p "require('./package.json').version")"
  check_version "src-tauri/Cargo.toml" \
    "$(awk '/^\[package\]/{p=1;next} /^\[/{p=0} p && /^version *=/{gsub(/[" ]/,"",$3); print $3; exit}' src-tauri/Cargo.toml)"
  check_version "sidecar/pyproject.toml" \
    "$(awk '/^\[project\]/{p=1;next} /^\[/{p=0} p && /^version *=/{gsub(/[" ]/,"",$3); print $3; exit}' sidecar/pyproject.toml)"
  check_version "sidecar/arcelle_sidecar/__init__.py" \
    "$(sed -n 's/^__version__ *= *"\(.*\)"/\1/p' sidecar/arcelle_sidecar/__init__.py | head -1)"

  # Toolchain-written lock files — regenerated by `cargo build` / `uv lock`.
  lock_version() {  # <lockfile> <package name>
    awk -v want="name = \"$2\"" '$0==want{f=1;next} f && /^version = /{gsub(/[" ]/,"",$3); print $3; exit}' "$1"
  }
  check_version "src-tauri/Cargo.lock" "$(lock_version src-tauri/Cargo.lock arcelle)"
  check_version "sidecar/uv.lock"      "$(lock_version sidecar/uv.lock arcelle-sidecar)"

  # ------------------------------------------------------------- changelog ---
  step "Changelog"
  if grep -q "^## ${VER} " CHANGELOG.md; then
    ok "CHANGELOG.md has a '## ${VER}' entry"
  else
    bad "CHANGELOG.md has no '## ${VER}' entry — the release notes come from it"
  fi

  # ------------------------------------------------------- bundled weights ---
  # tauri-build copies every bundle.resources path into the .app, so a MISSING
  # weight file fails the build loudly. A zero-byte STUB does not: CI touches
  # one for Whisper rather than download 574 MB, and a release built over that
  # ships an app whose on-device models silently do nothing. The weights are
  # gitignored, so the only place to notice is here.
  step "Bundled model weights"
  while read -r p; do
    [[ -n "$p" ]] || continue
    # bundle.resources paths are relative to tauri.conf.json's own directory.
    p="src-tauri/${p}"
    sz="$(stat -f%z "$p" 2>/dev/null || echo 0)"
    if [[ "$sz" -ge 100000 ]]; then
      ok "$p — ${sz} bytes"  # compare against RELEASING.md's table
    else
      bad "$p — ${sz} bytes, missing or a stub (RELEASING.md § On-device models)"
    fi
  done < <(node -p "Object.keys(require('./src-tauri/tauri.conf.json').bundle.resources).filter(k => k.startsWith('resources/models/')).join('\n')")

  # ------------------------------------------------------------ mock drift ---
  # A renamed command (`save_page` → `browse_save`) breaks only the shipped
  # build: the browser harness keeps answering the old name. `npm test` runs
  # this too, via e2e/page-script/mock-coverage.test.mjs — it is repeated here
  # so `--checks`, the fast pre-tag gate, does not skip it.
  step "Command drift (frontend ↔ host ↔ qa-mock)"
  if DRIFT="$(node qa/check-mock-coverage.mjs 2>&1)"; then
    ok "$(printf '%s' "$DRIFT" | tail -1)"
  else
    bad "frontend/host/qa-mock command drift"
    printf '%s\n' "$DRIFT" >&2
  fi
fi

# ------------------------------------------------------------------ suites ---
if [[ $CHECKS_ONLY -eq 0 ]]; then
  suite() {  # <label> <command…>
    step "$1"
    if "${@:2}"; then ok "$1"; else bad "$1"; fi
  }
  suite "TypeScript + Vite build" npm run build
  suite "Page-script contract"    npm run test:page
  # Homebrew's cargo ahead of a broken rustup shim, and /usr/bin ahead of any
  # Python shims, for the same reason release.sh prepends it.
  suite "Rust" env PATH="/opt/homebrew/bin:/usr/bin:/bin:$PATH" \
    cargo test --manifest-path src-tauri/Cargo.toml
  # `uv run` matters here: a bare pytest picks up the wrong environment.
  suite "Python sidecar" sh -c 'cd sidecar && uv run pytest -q'
fi

echo
if [[ $FAILED -ne 0 ]]; then
  echo "✗ FAILED — fix the above before tagging ${VER}" >&2
elif [[ $SUITES_ONLY -eq 1 ]]; then
  echo "✓ Every suite green"
else
  echo "✓ Preflight clean for ${VER} — safe to tag and run scripts/release.sh"
fi
exit $FAILED
