import type { AiActionDef } from "../shared/apiTypes.js";

export type AiActionSpec = AiActionDef;

export const AI_ACTIONS: readonly AiActionSpec[] = [
  {
    id: "summarize",
    title: "Summarize",
    description: "A one-line TL;DR and the key points.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Summarize this material: a one-line TL;DR, then the key points as a short list.",
  },
  {
    id: "analyze",
    title: "Analyze",
    description: "Structure, themes, sentiment, risks, and open questions.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Analyze this material: its structure, main themes, sentiment, risks, and open questions.",
  },
  {
    id: "explain",
    title: "Explain",
    description: "A plain-language walkthrough of the material.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Explain this material in plain language, as if to a smart friend new to the topic.",
  },
  {
    id: "extract",
    title: "Extract",
    description: "Entities, dates, figures, and action items as a table.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Extract the entities, dates, figures, and action items from this material.",
  },
  {
    id: "outline",
    title: "Outline",
    description: "A clean nested outline of the points.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Turn this material into a clean, nested outline of its points.",
  },
  {
    id: "rewrite",
    title: "Rewrite",
    description: "A tightened, clearer version.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Rewrite this material into a tighter, clearer version that keeps every point.",
  },
  {
    id: "qa_pack",
    title: "Q&A pack",
    description: "Study question-and-answer pairs.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Write a set of study question-and-answer pairs covering this material.",
  },
  {
    id: "fact_check",
    title: "Fact check",
    description: "Flag claims the material doesn't support.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Fact-check this material and flag any claim it doesn't actually support.",
  },
  {
    id: "translate",
    title: "Translate",
    description: "Translate the material into any language.",
    scope: "file",
    needsQuestion: false,
    needsLanguage: true,
    defaultPrompt: "Translate this material into the target language, keeping its structure.",
  },
  {
    id: "research",
    title: "Research",
    description: "Answer a question with a cited synthesis of the room.",
    scope: "room",
    needsQuestion: true,
    needsLanguage: false,
    defaultPrompt: "Answer the question using this room, and cite the files you draw on.",
  },
  {
    id: "compare",
    title: "Compare",
    description: "Diff the files side by side.",
    scope: "room",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Compare these files side by side — what they agree on and where they differ.",
  },
  {
    id: "timeline",
    title: "Timeline",
    description: "A chronology from the dated mentions.",
    scope: "room",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Build a chronological timeline from the dated events mentioned in this material.",
  },
  {
    id: "themes",
    title: "Themes",
    description: "Group the material into topic clusters.",
    scope: "room",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Group this material into its main themes, with the points under each.",
  },
  {
    id: "gaps",
    title: "Gaps",
    description: "What's missing given the rest of the room.",
    scope: "room",
    needsQuestion: false,
    needsLanguage: false,
    defaultPrompt: "Given this room, point out what's missing or still unanswered.",
  },
];

export function aiActionPrompts(): AiActionDef[] {
  return [...AI_ACTIONS];
}
