/** Stable file-storage facade; implementation is split by lifecycle domain. */
export {
  CHUNK_CAP,
  DERIVED_PREVIEW_DESTINATION,
  type FileMeta,
  type TrashedFile,
  stripHebrewMarks,
  inTransaction,
  insertChunks,
  clearChunks,
  currentDate,
  fileNamesHint,
  columnExists,
  tableExists,
  searchKey,
  LINKED,
  SECTION_ONLY,
  isWorkspaceDatabase,
} from "./filesModel.js";
export {
  insertFile,
  insertFileFromUrl,
  markSectionOnly,
  setLibraryVisibility,
  fileWithSameBytes,
  listFiles,
  listPublicFiles,
  listLibraryFiles,
  libraryFileCount,
  roomFileCount,
  newSourceFileCount,
  type FileBriefRow,
  listFilesBrief,
  placementNote,
  listFileInventory,
  type SummaryFile,
  listFilesForSummary,
  setFileAiSummary,
  setDerivedFrom,
} from "./filesCreateList.js";
export {
  type DerivedPreviewRef,
  markDerivedPreview,
  derivedPreviews,
  getDerivedPreview,
  derivedLinks,
  setMediaMeta,
  getMediaMeta,
  setWebMeta,
  getWebMeta,
  filesMissingSummary,
} from "./filesDerived.js";
export {
  fileByExactName,
  availableName,
  getFileMeta,
  getFileName,
  anyFileName,
  fileOriginUrl,
  getFileFull,
  getFileBytesNamed,
  getFileBytes,
  getFileExtractedText,
  updateFileContent,
  setFileExtractedText,
} from "./filesContent.js";
export {
  type TrashActor,
  trashActorParts,
  trashFile,
  restoreFile,
  listTrashedFiles,
  trashedFileCount,
  deleteFile,
  emptyTrash,
  renameFile,
} from "./filesTrash.js";
export {
  filesMissingText,
  filesWithBytes,
  findFileLike,
  findFileLikeQualified,
  findSourceFileLike,
  findFileLikeFull,
  findImageLike,
  filesNameLike,
  filesContentFts,
} from "./filesSearch.js";
